language: python
python:
  - "2.7"
  - "3.8"
before_install:
  - python --version
  - pip list
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
install:
  - pip install .
script:
  - pytest -vv --cov=pprofiler tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
